apiVersion: v1
kind: Secret
metadata:
  name: sampleapp-{{ .Release.Name }}-secrets
type: Opaque
data:
  mysqlUser: c2FtcGxlYXBw
  mysqlPassword: TmV0QXBwMTIz
  mysqlRootPassword: TmV0QXBwMTIz
  mysqlDatabase: c2FtcGxlYXBw
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sampleapp-{{ .Release.Name }}-redis-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redisVolumeSize }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-{{ .Release.Name }}-redis
spec:
  selector:
    matchLabels:
      app: sampleapp-{{ .Release.Name }}-redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sampleapp-{{ .Release.Name }}-redis
    spec:
      containers:
      - name: redis
        image: redis:5.0.5-alpine
        ports:
        - containerPort: 6379
          name: client
        - containerPort: 16379
          name: gossip
        volumeMounts:
        - name: data
          mountPath: /data
          readOnly: false
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: sampleapp-{{ .Release.Name }}-redis-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: sampleapp-{{ .Release.Name }}-redis-service
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
    name: client
  - port: 16379
    protocol: TCP
    targetPort: 16379
    name: gossip
  selector:
    app: sampleapp-{{ .Release.Name }}-redis
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sampleapp-{{ .Release.Name }}-config
data:
  appversion: "{{.Chart.Version}}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-{{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sampleapp-{{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 25%
       maxSurge: 1
  template:
    metadata:
      labels:
        app: sampleapp-{{ .Release.Name }}
    spec:
      containers:
      - name: sampleapp
        image: mminichino/sample-app:latest
        imagePullPolicy: Always
        command: ["node", "index.js"]
        ports:
        - name: nodejs-port
          containerPort: {{ .Values.nodePort }}
        env:
          - name: MYSQL_HOST
            value: sampleapp-{{ .Release.Name }}-db-service
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sampleapp-{{ .Release.Name }}-secrets
                key: mysqlRootPassword
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: sampleapp-{{ .Release.Name }}-secrets
                key: mysqlDatabase
          - name: APPVERSION
            valueFrom:
              configMapKeyRef:
                name: sampleapp-{{ .Release.Name }}-config
                key: appversion
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: REDIS_HOST
            value: sampleapp-{{ .Release.Name }}-redis-service
---
apiVersion: v1
kind: Service
metadata:
  name: sampleapp-{{ .Release.Name }}-service
  labels:
    app: sampleapp-{{ .Release.Name }}
spec:
  selector:
    app: sampleapp-{{ .Release.Name }}
  ports:
  - name: http
    port: {{ .Values.nodePort }}
    targetPort: {{ .Values.nodePort }}
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sampleapp-{{ .Release.Name }}-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: {{ .Values.externalPort }}
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sampleapp-{{ .Release.Name }}
spec:
  hosts:
  - "*"
  gateways:
  - sampleapp-{{ .Release.Name }}-gateway
  http:
  - route:
    - destination:
        host: sampleapp-{{ .Release.Name }}-service.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.nodePort }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sampleapp-{{ .Release.Name }}-db-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysqlVolumeSize }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-{{ .Release.Name }}-db
spec:
  selector:
    matchLabels:
      app: sampleapp-{{ .Release.Name }}-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sampleapp-{{ .Release.Name }}-db
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - name: mysql-port
          containerPort: 3306
        volumeMounts:
        - name: sampleapp-{{ .Release.Name }}-persistent-storage
          mountPath: /var/lib/mysql
          subPath: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sampleapp-{{ .Release.Name }}-secrets
                key: mysqlRootPassword
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: sampleapp-{{ .Release.Name }}-secrets
                key: mysqlUser
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sampleapp-{{ .Release.Name }}-secrets
                key: mysqlPassword
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: sampleapp-{{ .Release.Name }}-secrets
                key: mysqlDatabase
      volumes:
      - name: sampleapp-{{ .Release.Name }}-persistent-storage
        persistentVolumeClaim:
          claimName: sampleapp-{{ .Release.Name }}-db-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: sampleapp-{{ .Release.Name }}-db-service
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: sampleapp-{{ .Release.Name }}-db
