apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
  namespace: sampleapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sampleapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 25%
       maxSurge: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sample-app
        image: mminichino/sample-app:latest
        imagePullPolicy: Always
        command: ["node", "index.js"]
        ports:
        - name: nodejs-port
          containerPort: 8080
        env:
          - name: MYSQL_HOST
            value: sampleapp-db-service
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sampleapp-secrets
                key: mysqlRootPassword
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: sampleapp-secrets
                key: mysqlDatabase
          - name: APPVERSION
            valueFrom:
              configMapKeyRef:
                name: sampleapp-config
                key: appversion
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: REDIS_HOST
            value: sampleapp-redis-service
