apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sampleapp
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 25%
       maxSurge: 1
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sample-app
        image: mminichino/sample-app:1.2
        command: ["node", "index-db.js"]
        ports:
        - name: nodejs-port
          containerPort: 8080
        env:
          - name: MYSQL_HOST
            value: sampleapp-db-service
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sampleapp-secrets
                key: mysqlRootPassword
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: sampleapp-secrets
                key: mysqlDatabase
          - name: APPVERSION
            value: "1.2"
---
apiVersion: v1
kind: Service
metadata:
  name: sampleapp-service
  labels:
    app: sampleapp
spec:
  selector:
    app: sampleapp
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sampleapp-db-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ontapnas
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-db
spec:
  selector:
    matchLabels:
      app: sampleapp-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sampleapp-db
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - name: mysql-port
          containerPort: 3306
        volumeMounts:
        - name: sampleapp-persistent-storage
          mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sampleapp-secrets
                key: mysqlRootPassword
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: sampleapp-secrets
                key: mysqlUser
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sampleapp-secrets
                key: mysqlPassword
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: sampleapp-secrets
                key: mysqlDatabase
      volumes:
      - name: sampleapp-persistent-storage
        persistentVolumeClaim:
          claimName: sampleapp-db-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: sampleapp-db-service
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: sampleapp-db
