apiVersion: v1
kind: Secret
metadata:
  name: sampleapp-secrets
type: Opaque
data:
  mysqlUser: c2FtcGxlYXBw
  mysqlPassword: TmV0QXBwMTIz
  mysqlRootPassword: TmV0QXBwMTIz
  mysqlDatabase: c2FtcGxlYXBw
